CREATE DATABASE myDatabase;

use myDatabase;

CREATE TABLE user905(
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
password VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT  NULL,
country VARCHAR(255)  NOT NULL,
PRIMARY KEY(id));
